// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LanguagePack
{
    internal sealed partial class Vsix
    {
        public const string Id = "LanguagePack.da8ee435-6f16-40c1-a2e0-be6989294391";
        public const string Name = "Syntax Booster Pack";
        public const string Description = @"Provides syntax support for languages not currently supported by Visual Studio";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
